Bump

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -7,7 +7,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        ruby: ['2.7', '3.0', '3.1', '3.3']
+        ruby: ['3.1', '3.2', '3.3']
     steps:
     - uses: actions/checkout@v4
     - name: Set up Ruby
@@ -15,9 +15,17 @@ jobs:
       with:
         ruby-version: ${{ matrix.ruby }}
         bundler-cache: true
-    - name: Install Yarn dependencies
-      uses: Borales/actions-yarn@v4
+    - name: Cache Bundler
+      uses: actions/cache@v4
       with:
-        cmd: install
+        path: vendor/bundle
+        key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
+        restore-keys: |
+          ${{ runner.os }}-gems-${{ matrix.ruby }}-
+    - name: Install Dependencies
+      run: |
+        bundle install --jobs 4 --retry 3 || (echo "Bundle install failed, dumping logs" && cat ~/.bundle/cache/compact_index/* && exit 1)
+    - name: Run Security Audit
+      run: gem install bundler-audit && bundle audit
     - name: Run Tests
       run: bundle exec rake test
